### ISSUE TITLE
arm64 release

### ISSUE THREAD

**Issue by twk3** [dropseed/deps-git#10]
Currently deps fails on the m1/m2 macs when developers are running locally with git dependencies being checked.

```
deps -v upgrade

> Using component from https://github.com/dropseed/deps-git
> Storing component in /Users/<username>/Library/Caches/deps/components/deps-git
> git pull
Already up to date.
> Skipping install of /Users/<username>/Library/Caches/deps/components/deps-git
> Collecting with /Users/<username>/Library/Caches/deps/components/deps-git...
> Input path: .
> $DEPS_COMPONENT_PATH/bin/deps-git --collect . /var/folders/<key>/deps-958642410
sh: /Users/<username>/Library/Caches/deps/components/deps-git/bin/deps-git: No such file or directory
exit status 127
```

Any plans for releasing an arm64 version for this component?

**Comment by davegaeddert** [comment]
I'lll take a look at it. A lot of the Go tooling used here has effectively been deprecated by now... honestly I may just rewrite it in Python 3 unless that will cause any issues with your CI setup?

**Comment by twk3** [comment]
Well, we don't use the tag version pinning in the deps install script at the moment, so it would definitely break, and we would need to go in and add python3 to the image. But that part of it feels like its on us. (Now that fact that even if we DID pin the version, it wouldn't stop deps from installing the latest git-component, that's probably on you :wink: )

**Comment by davegaeddert** [comment]
Ha, fair enough — I noticed the version pinning thing too when looking at this again. I'll see if I can revive it in Go do a little cleanup.

**Comment by davegaeddert** [comment]
The latest release includes more binaries: https://github.com/dropseed/deps-git/releases/tag/0.4.0

Let me know if you have any issues/questions!
